backend/config/routes.rb
Rails.application.routes.draw do
  devise_for :players, :controllers => { :omniauth_callbacks => "players/omniauth_callbacks" }, :skip => [:sessions, :registration]
  devise_for :admins, :controllers => { :omniauth_callbacks => "admins/omniauth_callbacks" }, :skip => [:sessions, :registration]
  devise_scope :admins do
    get 'logout', to: 'backend/dashboard#logout', as: :destroy_admin_session
  end

  root :to => "home#index"
  get  'login', to: "home#login"
  get  'join', to: "home#join"
  get  'profile', to: "frontend/profile#index"
  
  namespace :backend do
    root :to => "rooms#index"
    resource :rooms
    resource :players do
      collection do
        get  'list', to: "players#index"
      end
    end
    get '/sessions/show', to: 'sessions#show', as: 'sessions_show'
  end  
end

backend/app/models/player.rb
class Player < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :validatable, :trackable, :omniauthable, omniauth_providers: [:steam]
  validates :name, uniqueness: true
  validates :account, uniqueness: true


  def self.from_omniauth(auth)
    where(uid: auth.uid).first_or_create do |player|
      player.uid = auth.uid
      player.name = auth.info.name
      player.nickname = auth.info.nickname
      player.location = auth.info.location
      player.image = auth.info.image
      player.password = Devise.friendly_token[0, 20]
    end
  end
end

backend/app/controllers/backend/dashboard_controller.rb
class Backend::DashboardController < ActionController::Base
    layout 'backend'
    before_action :authenticate_admin!

    def logout
        sign_out(current_admin)
        redirect_to backend_sessions_show_path
    end  
end

backend/app/controllers/backend/players_controller.rb
class Backend::PlayersController < Backend::DashboardController
    before_action :set_model, only: [:show]
    def index
        @players=Player.all
    end

    def show
        @rooms=RoomPlayer.where(player_id: @player.id)
          .joins("left join rooms on rooms.id = room_players.room_id")
          .select("room_players.*, rooms.name")
    end

    private
        def set_model
            @player=Player.find(params[:id])
        end
end

backend/app/controllers/backend/rooms_controller.rb
class Backend::RoomsController < Backend::DashboardController
    before_action :set_model, only: [:show, :edit, :update]
    def index
        @rooms=Room.all
    end

    def new
        @room=Room.new
    end
    
    def create
        @room = Room.new(room_params)
        respond_to do |format|
            if @room.save
                format.html { redirect_to backend_root_path, notice: 'Room was successfully created.' }
            else
                format.html { render :new }
            end
        end
    end

    def show 
    end

    def edit
    end
    
    def update
        respond_to do |format|
            if @room.update(room_params)
                format.html { redirect_to backend_root_path, notice: 'Room was successfully updated.' }
                format.json { render :show, status: :ok, location: @room }
            else
                format.html { render :edit }
                format.json { render json: @room.errors, status: :unprocessable_entity }
            end
        end
    end
    
    private
        def set_model
            if(params.has_key?(:id))
                @room=Room.find(params[:id])
            else     
                @room=Room.find(params[:room][:id])
            end
        end

        def room_params
            params.fetch(:room).permit(:id, :name, :full_cnt, :match_cnt, :status, :method, :place_cnt, :ticket, :time_limit)
        end
end

backend/app/controllers/backend/sessions_controller.rb
class Backend::SessionsController < ApplicationController
  before_action :checkuser, only: [:show]
  layout nil
  def show

  end

  def checkuser
    if current_admin.present?
      redirect_to backend_root_path
    end
  end

end

backend/app/controllers/players/omniauth_callbacks_controller.rb
class Players::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    skip_before_action :verify_authenticity_token, only: [:steam, :failure]
    def steam
        @player = Player.from_omniauth(request.env["omniauth.auth"])
        @player.save(:validate => false)
        if @player.present?
            sign_in_and_redirect @player, event: :authentication
        else
            
        end
    end

    def failure
        redirect_to root_path
    end
end

backend/app/helpers/backend/players_helper.rb
module Backend::PlayersHelper
end

backend/app/views/backend/players/index.html.erb
<% content_for :navbar, "Player Manage" %>
<div class="row">
    <div class="col-md-12">
        <div class="card strpied-tabled-with-hover">
            <div class="card-header ">
                <h4 class="card-title">Players</h4>
            </div>
            <div class="card-body table-full-width table-responsive">
                <table class="table table-hover table-striped">
                    <thead>
                        <th>ID</th>
                        <th>Name</th>
                        <th>UID</th>
                        <th>Account</th>
                        <th>Status</th>
                        <th>Created At</th>
                        <th></th>
                    </thead>
                    <tbody>
                        <% @players.each_with_index do |r, index| %>
                            <tr>
                                <td><%=index+1%></td>
                                <td><%=r.name%></td>
                                <td><%=r.uid%></td>
                                <td><%=r.account%></td>
                                <td><%=r.status%></td>
                                <td><%=r.created_at%></td>
                                <td>
                                   <a class="btn btn-primary btn-sm" href="<%=backend_players_path({id: r})%>" role="button">
                                    <%= t('action.show')%>
                                   </a>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

backend/app/views/backend/players/show.html.erb
<div class="row">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Rooms</h4>
            </div>
            <div class="card-body">
                <div class="card-body table-full-width table-responsive">
                    <table class="table table-hover table-striped">
                        <thead>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Join At</th>
                            <th></th>
                        </thead>
                        <tbody>
                            <% @rooms.each_with_index do |r, index| %>
                                <tr>
                                    <td><%=index+1%></td>
                                    <td><%=r.name%></td>
                                    <td><%=r.created_at%></td>
                                    <td></td>
                                </tr>  
                            <%end%>      
                        </tbody>            
                    </table> 
                </div>    
            </div>
        </div>    
    </div>
    <div class="col-md-4">
        <div class="card card-user">
            <div class="card-image">
                <img src="https://ununsplash.imgix.net/photo-1431578500526-4d9613015464?fit=crop&amp;fm=jpg&amp;h=300&amp;q=75&amp;w=400" alt="...">
            </div>
            <div class="card-body">
                <div class="author">
                    <a href="#">
                        <img class="avatar border-gray" src="<%=@player.image%>" alt="...">
                        <h5 class="title"><%=@player.name%></h5>
                    </a>
                    <p class="description">
                        <%=@player.nickname%>
                    </p>
                </div>
                <p class="description text-center">
                    <%=t('title.uid')%>:&nbsp;<%=@player.uid%>
                </p>
                <p class="description text-center">
                    <%=t('title.account')%>:&nbsp;<%=@player.account%>
                </p>
                <p class="description text-center">
                    <%=t('title.email')%>:&nbsp;<%=@player.email%>
                </p>
                <p class="description text-center">
                    <%=t('title.sign_in_count')%>:&nbsp;<%=@player.sign_in_count%>
                </p>
                <p class="description text-center">
                    <%=t('title.last_sign_in_at')%>:&nbsp;<%=@player.last_sign_in_at%>
                </p>
                <p class="description text-center">
                    <%=t('title.location')%>:&nbsp;<%=@player.location%>
                </p>
            </div>
            <hr>
            <div class="button-container mr-auto ml-auto">
                <button href="#" class="btn btn-simple btn-link btn-icon">
                    <i class="fa fa-facebook-square"></i>
                </button>
                <button href="#" class="btn btn-simple btn-link btn-icon">
                    <i class="fa fa-twitter"></i>
                </button>
                <button href="#" class="btn btn-simple btn-link btn-icon">
                    <i class="fa fa-google-plus-square"></i>
                </button>
            </div>
        </div>
    </div>
</div>    