backend/config/routes.rb
Rails.application.routes.draw do
  devise_for :players, :controllers => { :omniauth_callbacks => "players/omniauth_callbacks" }, :skip => [:sessions, :registration]
  devise_for :admins, :controllers => { :omniauth_callbacks => "admins/omniauth_callbacks" }, :skip => [:sessions, :registration]
  devise_scope :admins do
    get 'logout', to: 'backend/dashboard#logout', as: :destroy_admin_session
  end

  root :to => "home#index"
  get  'login', to: "home#login"
  get  'join', to: "home#join"
  get  'profile', to: "frontend/profile#index"
  
  namespace :backend do
    root :to => "rooms#index"
    resource :rooms
    resource :players do
      collection do
        get  'list', to: "players#index"
      end
    end
    get '/sessions/show', to: 'sessions#show', as: 'sessions_show'
  end  
end

backend/app/models/room.rb
class Room < ApplicationRecord
    def calc 
       if self.method==METHOD_NORMAL
        return self.calc_normal()
       elsif self.method==WINORLOSE
        return self.calc_winorlose()
       end
       return nil
    end   

    def calc_normal()
        Match.select('players.id, players.name, SUM((kills*16)+ppoints.point) as cp')
        .joins('left join players on matches.player_id=players.id')
        .joins('left join ppoints on ppoints.id=matches.win_place')
        .where(room_id: self.id).group('player_id')
        .order('cp desc')
    end
    
    def self.calc_winorlose()
  
    end 
end

backend/app/controllers/backend/dashboard_controller.rb
class Backend::DashboardController < ActionController::Base
    layout 'backend'
    before_action :authenticate_admin!

    def logout
        sign_out(current_admin)
        redirect_to backend_sessions_show_path
    end  
end

backend/app/controllers/backend/players_controller.rb
class Backend::PlayersController < Backend::DashboardController
    before_action :set_model, only: [:show]
    def index
        @players=Player.all
    end

    def show
        @rooms=RoomPlayer.where(player_id: @player.id)
          .joins("left join rooms on rooms.id = room_players.room_id")
          .select("room_players.*, rooms.name")
    end

    private
        def set_model
            @player=Player.find(params[:id])
        end
end

backend/app/controllers/backend/rooms_controller.rb
class Backend::RoomsController < Backend::DashboardController
    before_action :set_model, only: [:show, :edit, :update]
    def index
        @rooms=Room.all
    end

    def new
        @room=Room.new
    end
    
    def create
        @room = Room.new(room_params)
        respond_to do |format|
            if @room.save
                format.html { redirect_to backend_root_path, notice: 'Room was successfully created.' }
            else
                format.html { render :new }
            end
        end
    end

    def show 
    end

    def edit
    end
    
    def update
        respond_to do |format|
            if @room.update(room_params)
                format.html { redirect_to backend_root_path, notice: 'Room was successfully updated.' }
                format.json { render :show, status: :ok, location: @room }
            else
                format.html { render :edit }
                format.json { render json: @room.errors, status: :unprocessable_entity }
            end
        end
    end
    
    private
        def set_model
            if(params.has_key?(:id))
                @room=Room.find(params[:id])
            else     
                @room=Room.find(params[:room][:id])
            end
        end

        def room_params
            params.fetch(:room).permit(:id, :name, :full_cnt, :match_cnt, :status, :method, :place_cnt, :ticket, :time_limit)
        end
end

backend/app/controllers/backend/sessions_controller.rb
class Backend::SessionsController < ApplicationController
  before_action :checkuser, only: [:show]
  layout nil
  def show

  end

  def checkuser
    if current_admin.present?
      redirect_to backend_root_path
    end
  end

end

backend/app/helpers/backend/players_helper.rb
module Backend::PlayersHelper
end

backend/app/views/backend/rooms/_form.html.erb
<div class="row">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title"><%=title%></h4>
            </div>
            <div class="card-body">
                <%= form_for :room, url: backend_rooms_path, :method => method do |f| %>
                    <%if @room.id.present?%>
                        <%= f.hidden_field(:id, :value => @room.id)%>
                    <%end%>
                    <div class="row">
                        <div class="col-md-5 pr-1">
                            <div class="form-group">
                                <label><%= t('lbl.name')%></label>
                                <%= f.text_field :name, class: "form-control", required: true %>
                            </div>
                        </div>
                        <div class="col-md-3 px-1">
                            <div class="form-group">
                                <label><%= t('lbl.full_cnt')%></label>
                                <%= f.number_field :full_cnt, class: "form-control", required: true %>
                            </div>
                        </div>
                        <div class="col-md-4 pl-1">
                            <div class="form-group">
                                <label><%= t('lbl.match_cnt')%></label>
                                <%= f.number_field :match_cnt, class: "form-control", required: true %>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 pr-1">
                            <div class="form-group">
                                <label><%= t('lbl.place_cnt')%></label>
                                <%= f.number_field :place_cnt, class: "form-control", required: true %>
                            </div>
                        </div>
                        <div class="col-md-4 pl-1">
                            <div class="form-group">
                                <label><%= t('lbl.ticket')%></label>
                                <%= f.number_field :ticket, class: "form-control", required: true %>
                            </div>
                        </div>
                        <div class="col-md-4 pl-1">
                            <div class="form-group">
                                <label><%= t('lbl.time_limit')%></label>
                                <%= f.number_field :time_limit, class: "form-control", required: true %>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 pr-1">
                            <div class="form-group">
                                <label><%= t('lbl.status')%></label>
                                <%= f.select :status, options_for_select([['Open', ROOM_OPEN], ['Closed', ROOM_CLOSED], ['Finished', ROOM_FINISHED]],@room.status), {:include_blank => true}, {class: "form-control", required: true} %>
                            </div>
                        </div>
                        <div class="col-md-6 pr-1">
                            <div class="form-group">
                                <label><%= t('lbl.method')%></label>
                                <%= f.select :method, options_for_select([['Normal', METHOD_NORMAL], ['Simple', METHOD_SIMPLE]],@room.method), {:include_blank => true}, {class: "form-control", required: true} %>
                            </div>
                        </div>
                    </div>    
                    
                    <button type="submit" class="btn btn-info btn-fill pull-right"><%=t('action.submit')%></button>
                    <div class="clearfix"></div>
                <% end %>
            </div>
        </div>
    </div>
</div>

backend/app/views/backend/rooms/edit.html.erb
<%= render 'form', :title => t('title.room_edit'), :method=>"PUT"%>

backend/app/views/backend/rooms/index.html.erb
<% content_for :navbar, "Room Manage" %>
<div class="row">
    <div class="col-md-12">
        <div class="card strpied-tabled-with-hover">
            <div class="card-header ">
                <h4 class="card-title">Rooms</h4>
                <div class="card-action">
                  <a class="btn btn-primary btn-sm" href="<%=new_backend_rooms_path%>" role="button">Нэмэх</a>
                </div>
            </div>
            <div class="card-body table-full-width table-responsive">
                <table class="table table-hover table-striped">
                    <thead>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Ticket</th>
                        <th>Full Cnt</th>
                        <th>Member Cnt</th>
                        <th>Time Limit</th>
                        <th>Amount</th>
                        <th>Status</th>
                        <th>Created At</th>
                        <th></th>
                    </thead>
                    <tbody>
                        <% @rooms.each_with_index do |r, index| %>
                            <tr>
                                <td><%=index+1%></td>
                                <td><%=r.name%></td>
                                <td><%=r.ticket%></td>
                                <td><%=r.full_cnt%></td>
                                <td><%=r.member_cnt%></td>
                                <td><%=r.time_limit%></td>
                                <td><%=r.amount%></td>
                                <td><%=r.status%></td>
                                <td><%=r.created_at%></td>
                                <td>
                                   <a class="btn btn-primary btn-sm" href="<%=edit_backend_rooms_path({id: r})%>" role="button">
                                    <%= t('action.edit')%>
                                   </a>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

backend/app/views/backend/rooms/new.html.erb
<%= render 'form', :title => t('title.room_new'), :method=>"POST"%>

backend/app/views/backend/rooms/show.html.erb
hello this is room 