backend/config/routes.rb
Rails.application.routes.draw do
  devise_for :players, :controllers => { :omniauth_callbacks => "players/omniauth_callbacks" }, :skip => [:sessions, :registration]
  devise_for :admins, :controllers => { :omniauth_callbacks => "admins/omniauth_callbacks" }, :skip => [:sessions, :registration]
  devise_scope :admins do
    get 'logout', to: 'backend/dashboard#logout', as: :destroy_admin_session
  end

  root :to => "home#index"
  get  'login', to: "home#login"
  get  'join', to: "home#join"
  get  'profile', to: "frontend/profile#index"
  
  namespace :backend do
    root :to => "rooms#index"
    resource :rooms
    resource :players do
      collection do
        get  'list', to: "players#index"
      end
    end
    get '/sessions/show', to: 'sessions#show', as: 'sessions_show'
  end  
end

backend/app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :registerable,
   :validatable, :omniauthable, omniauth_providers: [:google_oauth2]
    def self.find_from_auth_hash(auth)
        
        admin=where(provider: auth.provider, email: auth.info.email).first
        if admin.present?
            admin.provider = auth.provider
            admin.uid = auth.uid
            admin.name = auth.info.first_name
            admin.email = auth.info.email
            admin.save!
        end
        return admin
    end
end  

backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

backend/app/models/invoice.rb
class Invoice < ApplicationRecord
end

backend/app/models/job.rb
class Job < ApplicationRecord
    validates :name, uniqueness: true
end
  

backend/app/models/match.rb
class Match < ApplicationRecord
  validates :player_id, uniqueness: { scope: :match }
end

backend/app/models/player.rb
class Player < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :validatable, :trackable, :omniauthable, omniauth_providers: [:steam]
  validates :name, uniqueness: true
  validates :account, uniqueness: true


  def self.from_omniauth(auth)
    where(uid: auth.uid).first_or_create do |player|
      player.uid = auth.uid
      player.name = auth.info.name
      player.nickname = auth.info.nickname
      player.location = auth.info.location
      player.image = auth.info.image
      player.password = Devise.friendly_token[0, 20]
    end
  end
end

backend/app/models/ppoint.rb
class Ppoint < ApplicationRecord
end  

backend/app/models/room.rb
class Room < ApplicationRecord
    def calc 
       if self.method==METHOD_NORMAL
        return self.calc_normal()
       elsif self.method==WINORLOSE
        return self.calc_winorlose()
       end
       return nil
    end   

    def calc_normal()
        Match.select('players.id, players.name, SUM((kills*16)+ppoints.point) as cp')
        .joins('left join players on matches.player_id=players.id')
        .joins('left join ppoints on ppoints.id=matches.win_place')
        .where(room_id: self.id).group('player_id')
        .order('cp desc')
    end
    
    def self.calc_winorlose()
  
    end 
end

backend/app/models/room_player.rb
class RoomPlayer < ApplicationRecord
  validates :player_id, uniqueness: { scope: :room_id }
end

backend/app/models/transaction.rb
class Transaction < ApplicationRecord
end

backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

backend/app/controllers/backend/players_controller.rb
class Backend::PlayersController < Backend::DashboardController
    before_action :set_model, only: [:show]
    def index
        @players=Player.all
    end

    def show
        @rooms=RoomPlayer.where(player_id: @player.id)
          .joins("left join rooms on rooms.id = room_players.room_id")
          .select("room_players.*, rooms.name")
    end

    private
        def set_model
            @player=Player.find(params[:id])
        end
end

backend/app/controllers/backend/rooms_controller.rb
class Backend::RoomsController < Backend::DashboardController
    before_action :set_model, only: [:show, :edit, :update]
    def index
        @rooms=Room.all
    end

    def new
        @room=Room.new
    end
    
    def create
        @room = Room.new(room_params)
        respond_to do |format|
            if @room.save
                format.html { redirect_to backend_root_path, notice: 'Room was successfully created.' }
            else
                format.html { render :new }
            end
        end
    end

    def show 
    end

    def edit
    end
    
    def update
        respond_to do |format|
            if @room.update(room_params)
                format.html { redirect_to backend_root_path, notice: 'Room was successfully updated.' }
                format.json { render :show, status: :ok, location: @room }
            else
                format.html { render :edit }
                format.json { render json: @room.errors, status: :unprocessable_entity }
            end
        end
    end
    
    private
        def set_model
            if(params.has_key?(:id))
                @room=Room.find(params[:id])
            else     
                @room=Room.find(params[:room][:id])
            end
        end

        def room_params
            params.fetch(:room).permit(:id, :name, :full_cnt, :match_cnt, :status, :method, :place_cnt, :ticket, :time_limit)
        end
end

backend/app/controllers/backend/sessions_controller.rb
class Backend::SessionsController < ApplicationController
  before_action :checkuser, only: [:show]
  layout nil
  def show

  end

  def checkuser
    if current_admin.present?
      redirect_to backend_root_path
    end
  end

end

backend/app/controllers/base_controller.rb
class BaseController < ApplicationController
    before_action :authenticate_player!
end

backend/app/controllers/frontend/profile_controller.rb
class Frontend::ProfileController < BaseController
    def index
    end
end   

backend/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    players = "Sindustry"
    players="HiT-MuseSummit-"
    #last=Pubg.player(players)
    last=Pubg.last_match(players)
    puts "----------------"
    puts current_player
    puts d1=ApplicationHelper.date_convert("2019-06-21T05:22:56Z")
    puts ApplicationHelper.date_minus(d1,Time.now)
    puts "----------------"
    #id="6e0a498d-33c4-4cfa-9b85-23958f638a02"
    id= "60b55684-ed87-41b9-911e-479f41168dd2"
    player_id="account.b93134c0dbdf488cbb0a94e460a0baec"
    #Pubg.matches(id,player_id)
    #MatchJob.run()
    puts "----------------"
    room=Room.find(1)
    @players=room.calc
    puts "----------------"
  end
  
  def login 
    puts "----------------"
    room=Room.find(1)
    @players=room.calc
    puts "----------------"
  end
  
  def join
    result=Hash.new
    result[:status]=400
    player=Player.where(name: "HiT-MuseSummit-").first
    #player=current_player
    room=Room.where(status: ROOM_OPEN).first
    if player.present? and room.present? and room.full_cnt>room.member_cnt
      last_match=Pubg.last_match(player.name)
      if last_match.present?
        player.update_attribute(:account, last_match[:account])
        rp=RoomPlayer.new
        rp.room_id=room.id
        rp.player_id=player.id
        rp.last_match=last_match[:match]
        if rp.save
          room.member_cnt=room.member_cnt+1
          if room.full_cnt==room.member_cnt
            room.status=ROOM_CLOSED
          end 
          room.save!
          result[:status]=200
        else
          result[:status]=400
        end
      end
    end
    render json: result
  end
end

backend/app/controllers/payment_controller.rb
class PaymentController < BaseController   
end

backend/app/helpers/application_helper.rb
module ApplicationHelper
  def self.date_convert(str_date)
    begin
      dd=str_date.to_time
      zone=ActiveSupport::TimeZone.new(BEIJING)
      return dd.in_time_zone(zone)
    rescue => e
      return nil
    end
  end

  def self.date_minus(d1,d2)
    return ((d1 - d2)/60).to_i #minutes
  end
  
  def active_class(link_path)
    current_page?(link_path) ? "nav-item active" : "nav-item"
  end

end

backend/app/helpers/backend/players_helper.rb
module Backend::PlayersHelper
end

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pubgmongolia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

backend/app/views/layouts/backend.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>RaceIT Admin</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <%= stylesheet_link_tag    'backend', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'backend', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="wrapper">
          <div class="sidebar">
              <div class="sidebar-wrapper">
                  <div class="logo">
                      <a href="/" target='_blank' class="simple-text">
                          RaceIT
                      </a>
                  </div>
                  <ul class="nav">
                      <li class="<%=active_class(backend_root_path)%>">
                          <a class="nav-link" href="<%=backend_root_path%>">
                              <i class="nc-icon nc-notes"></i>
                              <p>Rooms</p>
                          </a>
                      </li>
                      <li class="<%=active_class(list_backend_players_path)%>">
                          <a class="nav-link" href="<%=list_backend_players_path%>">
                              <i class="nc-icon nc-circle-09"></i>
                              <p>Players</p>
                          </a>
                      </li>
                      
                  </ul>
              </div>
          </div>
          <div class="main-panel">
              <!-- Navbar -->
              <nav class="navbar navbar-expand-lg " color-on-scroll="500">
                  <div class="container-fluid">
                      <a class="navbar-brand" href="#"><%=yield(:navbar)%></a>
                      
                      <div class="collapse navbar-collapse justify-content-end" id="navigation">
                          
                          <ul class="navbar-nav ml-auto">
                              <li class="nav-item">
                                  <a class="nav-link" href="#">
                                      <span class="no-icon"><%=current_admin.name%></span>
                                  </a>
                              </li>
                              <li class="nav-item">
                                  <a class="nav-link" href="<%=destroy_admin_session_path%>">
                                      <span class="no-icon">Log out</span>
                                  </a>
                              </li>
                          </ul>
                      </div>
                  </div>
              </nav>
              <!-- End Navbar -->
              <div class="content">
                  <div class="container-fluid">
                      <%= yield %>
                  </div>
              </div>
              <footer class="footer">
                  <div class="container-fluid">
                      <nav>
                          <ul class="footer-menu">
                              <li>
                                  <a href="/" target='_blank'>
                                      Home
                                  </a>
                              </li>
                              <li>
                                  <a href="#">
                                      Company
                                  </a>
                              </li>
                          </ul>
                          <p class="copyright text-center">
                              ©
                              <script>
                                  document.write(new Date().getFullYear())
                              </script>
                              <a href="">RaceIT</a>
                          </p>
                      </nav>
                  </div>
              </footer>
          </div>
      </div>
    </body>
</html>